// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package docs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/appkrafterrz/kraft-ui/web/components"
	"github.com/appkrafterrz/kraft-ui/web/layouts"
)

func ThemingPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mb-8\"><h1 class=\"text-3xl font-bold tracking-tight mb-3\">Theming</h1><p class=\"text-text-secondary text-lg\">kraft-ui uses Tailwind CSS v4's <code class=\"font-mono text-sm\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("@")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/docs/theming.templ`, Line: 13, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "theme</code> block. Override any token to match your brand — zero config changes needed.</p></div><h2 class=\"text-xl font-semibold mb-4 mt-10 pt-6 border-t border-border\">Design Token Catalog</h2><p class=\"text-text-secondary mb-4\">All tokens are CSS custom properties defined in <code class=\"font-mono text-xs\">tailwind.css</code>. Override only what you need.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock(components.CodeBlockProps{
				Title:    "tailwind.css",
				Language: "css",
				Code: `@import "tailwindcss";

@theme {
  /* ── Brand — change this to match your product ────── */
  --color-brand-500: oklch(55% 0.185 260);   /* primary */
  --color-brand-600: oklch(46% 0.175 260);   /* hover */
  --color-brand-700: oklch(38% 0.155 260);   /* active */
  --color-brand-50:  oklch(97.5% 0.012 260); /* light tints */
  --color-brand-100: oklch(94% 0.030 260);

  /* ── Surface & border ─────────────────────────────── */
  --color-surface:        white;
  --color-surface-muted:  oklch(97.5% 0 0);
  --color-surface-subtle: oklch(95% 0 0);
  --color-border:         oklch(88% 0 0);

  /* ── Text ─────────────────────────────────────────── */
  --color-text-primary:   oklch(12% 0 0);
  --color-text-secondary: oklch(42% 0 0);
  --color-text-muted:     oklch(62% 0 0);

  /* ── Semantic ─────────────────────────────────────── */
  --color-success-500: oklch(55% 0.18 155);
  --color-warning-500: oklch(72% 0.20 85);
  --color-error-500:   oklch(55% 0.22 25);
  --color-info-500:    oklch(58% 0.17 230);

  /* ── Border radius ────────────────────────────────── */
  --radius-md:  0.375rem;  /* most components */
  --radius-lg:  0.5rem;    /* cards */
  --radius-xl:  0.75rem;   /* modals, sheets */

  /* ── Typography ───────────────────────────────────── */
  --font-sans: "Inter", ui-sans-serif, system-ui, sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, monospace;
}`,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <h2 class=\"text-xl font-semibold mb-4 mt-10 pt-6 border-t border-border\">One-line brand change</h2><p class=\"text-text-secondary mb-4\">Changing your brand is literally one line. Switch from blue to green:</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock(components.CodeBlockProps{
				Language: "css",
				Code: `/* Blue (default) */
--color-brand-500: oklch(55% 0.185 260);

/* Switch to green */
--color-brand-500: oklch(55% 0.185 155);

/* Switch to orange */
--color-brand-500: oklch(65% 0.20 50);`,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <p class=\"text-text-secondary mt-3 text-sm\">Use <a href=\"https://oklch.com\" target=\"_blank\" class=\"text-brand-500 hover:underline\">oklch.com</a> to pick colors — OKLCH gives perceptually uniform brightness across hues.</p><h2 class=\"text-xl font-semibold mb-4 mt-10 pt-6 border-t border-border\">Dark mode</h2><p class=\"text-text-secondary mb-4\">Override surface and text tokens inside a <code class=\"font-mono text-xs\">.dark</code> class or <code class=\"font-mono text-xs\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("@")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/docs/theming.templ`, Line: 83, Col: 135}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "media (prefers-color-scheme: dark)</code>:</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock(components.CodeBlockProps{
				Language: "css",
				Code: `@media (prefers-color-scheme: dark) {
  :root {
    --color-surface:        oklch(15% 0 0);
    --color-surface-muted:  oklch(18% 0 0);
    --color-surface-subtle: oklch(20% 0 0);
    --color-border:         oklch(28% 0 0);
    --color-text-primary:   oklch(96% 0 0);
    --color-text-secondary: oklch(70% 0 0);
    --color-text-muted:     oklch(50% 0 0);
  }
}`,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.DocsShell(layouts.Meta{Title: "Theming", Description: "Customize kraft-ui with CSS design tokens."}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
